version: '3.7'

services:
  db:
    image: postgres:15-alpine
    command: >
      postgres
      -c log_statement=all
      -c max_connections=1000
      -c log_connections=true
      -c log_disconnections=true
      -c log_duration=true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./.docker:/docker-entrypoint-initdb.d

      - type: tmpfs
        target: /var/lib/postgresql/data
        tmpfs:
          size: 4294967296  # 4 GB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - dokploy-network

  redis:
    image: redis:5.0.5
    networks:
      - dokploy-network

  adminer:
    image: adminer
    command: ["php", "-S", "0.0.0.0:8081", "-t", "/var/www/html"]
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      DATABASE_URL: "postgres://myapp_dev:secret@db:5432/myapp_dev?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dokploy-network

  app:
    build: .
    ports:
      - "8000"
    environment:
      DATABASE_URL: "postgres://myapp_dev:secret@db:5432/myapp_dev?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`dokploy-demo.kafkai.io`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certResolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=8000"

networks:
  dokploy-network:
    external: true
